@startuml
salt
{
{T
  +Add Highscores
  ++Goal
  +++To add a Highscore to the Database
  ++Entry Conditions
  +++User must be in Score Fragment
  ++Scenario
  +++User enters username on Score Fragment.
  +++User presses the Enter button.
  +++User and score are added to the Database.
  +++System displays all Highscores.
  ++Exceptions
  +++none.
  ++Exit Conditions
  +++Successful Exit Conditions
  ++++Highscores are now visible.
  +++Failure Exit Conditions
  ++++Highschores are not visible.
}
}
@enduml